### PR TITLE
battery model + constraint fix

### PR DESCRIPTION
**Pull request by tanushree-sharma**
**Summary:** This PR implements the new solar + battery model that in previous versions was not using the binding demand constraints. There is also a fix added to the solar model where the E value is now multiplied by 0.35. 

**Changes Made:**
Solar and Battery Model: Removed constraint 3 that we previously had and updated it to the seasonal demand constraint. See Google doc for updated formulations [Solar](https://docs.google.com/document/d/1GwWiPQhJJH-AfhtBcXD5o0lrhU48I_JxCCM3-pXSHU8/edit), [Solar + Battery](https://docs.google.com/document/d/1gDXTdPqfVECZeornEdTnbza1oGXGkAopldhK6Ql3LTA/edit)

**Testing:**
Run the solar and solar + battery models. Ensure the results make sense -> solar + battery recommends more panels than just solar

**Additional Notes:**
To discuss if we want to use average lifetime electricity demand values or just on year 1 in the constraint (not a big deal with the output, more a logic concern)

### CODE REVIEW

**Comment by toni-li** [comment]
I've tested the changes out by keeping the inputs constant across the solar and solar + battery model to ensure that we're seeing different results. After running test cases that varied E0, month, and heating type, it appears that we do indeed see an increase in the optimal number of solar panels in the solar + battery model which is great to see!

I've also tested the corner case of a budget that is too small to fulfill 35% of the demand + battery and it works fine.

The only concern I have is with the outputted graphs. Currently, the cost savings are calculated based on Gts which is the on-peak electricity price, but since a part of the cost savings comes from the battery, wouldn't we have to split the cost savings calculations into on-peak savings and off-peak savings? 

thoughts @tanushree-sharma @gmalekan @orianaco?

**Comment by tanushree-sharma** [comment]
Good point Toni. How is something like this to find out how much electricity demand comes from battery: 
(y * electricity generated/panel/day) - 0.35*demand/day = electricity that goes into the battery/day

electricity that goes into the battery/day would then need to be converted to /season and then multiplied by off peak pricing to get savings

**Comment by toni-li** [comment]
That is exactly what I was thinking, Tanu! 

Should we sort this PR first and then open another one to implement those changes or just lump it all in one?

**Comment by tanushree-sharma** [comment]
Yay! Lets push this out first before making that change.

Any doubts @orianaco @gmalekan or are we good to merge?

**Pull request merged**
