### PR TITLE
Fix neg objfunc

### PR DESCRIPTION
**Pull request by tanushree-sharma**
**Summary:** This PR resolves the issue of the negative objective function value that arose because there was more electricity being generated than needed. 

**Changes Made:**
- Kept the Pn calculation and constraint. Tbh I’m not sure if its needed. It acts as an upper bound so I figured no harm in keeping it
- Added constraints for each season to make sure that more electricity than is needed is not greater than what is generated for each season averaged out for the lifetime of the panels
- Removed that MAX calculation for the seasonal costs with solar. This is no longer needed since that calculation should always be >=0 with the added constraints

**Testing:**
Ensure that output for a variety of parameters inputs make sense 
Specifically - Try using month = 1 for the electric model. Observe that there is no longer a negative objective function value. Ensure that yearly cost with and without solar graph does not show any negative costs

**Additional Notes:** Only applied the changes to the solar-model as the objective function for the solar + battery model is to be updated to reflect changes discussed in the last meeting. I started working on this before the delete U PR was merged so it includes U. Once the logic for this PR is good, I can remove the U value from the constraints I added and resolve the conflicts (for some reason I can only resolve conflicts before merging)

### CODE REVIEW

**Comment by toni-li** [comment]
Hi Tan,

Once again, great work! While testing out different months, I've noticed that the optimal number of solar panels to invest in ranges from 5 - 16 panels. I know that this has to do with the forecasted demand based on the seasons, but it seems like quite a large difference. I remember that when I looked at a previous PR on the forecasted demand the difference between seasons was large so maybe this is just something to note instead of an actual issue.

Another thing that I noticed was that when month = 1 and the heating is type electric, the optimal number of solar panels is 5 whereas if I change the heating type to natural gas, then the optimal number of solar panels becomes 16. I'm a little confused by this because if the homeowner relied on electricity for heating, wouldn't that mean that they need **more** solar panels to cover their demand vs. homeowners that rely on natural gas? 

Toni

**Comment by tanushree-sharma** [comment]
Hey Toni, thanks for your thorough analysis! I can explain why there's such variability in the optimal y value during our meeting Thursday.

**Comment by toni-li** [comment]
Awesome, much appreciated!

Any insight on the confusion I had on the optimal number of solar panels given an input of electric vs. natural gas?

Toni

**Comment by tanushree-sharma** [comment]
Both the variability of the different months and electric vs natural gas are the result of the same reason. They depend on the if, else statements from lines 11-26. The code logic for the specific cases you've mentioned is as follows:
- For electric heating, the code would enter the first if statement > first nested if. 
- For natural gas, the code would enter the first else statement > nested else. 
As you can see, they the factors that they are divided or multiplied by vary and it's due to these that the optimal y value for the two scenarios are so different. 

The results make sense because if homeowners rely on electricity for heating and they enter their demand amount in the winter months, that means that the demand amount inputted is their peak value and in spring and fall its approximately 1/3 of that. In order to not have excess supply in spring and fall, the system requires a low amount of solar panels. 

This isn't the case with natural gas since the demand amount inputted in winter is the same for spring and fall and the summer value is inflated. Essentially, the demand inputted directly acts as the lower bound which which leads to a high amount of solar panels in order to not have excess supply in the spring, fall, winter seasons. 

I hope that made sense, we can discuss during the meeting if you need me to clarify further.

**Pull request merged**
